### ISSUE TITLE
Lack of requirement files, dependencies, or environment

### ISSUE THREAD

**Issue by dinhanhx** [deep-spin/infinite-former#8]
As the title said, how do we set up the project properly? Could you provide at least the instruction to setup things?

**Comment by mrceresa** [comment]
I was also wondering if there has been any update on this!

**Comment by pedrohenriqueamartins** [comment]
I'll add a requirements file in the next days. However, I think for the sorting task you'll only need to install pytorch and to fine-tune gpt2 you'll need to install the transformer package as described in the README file.

**Comment by mrceresa** [comment]
Thanks Pedro! It's a very nice work: I'm going through the code and I'm impressed by the code
