### ISSUE TITLE
data files (data_sort_8000_train.txt)

### ISSUE THREAD

**Issue by carrtesy** [deep-spin/infinite-former#9]
Hi,
I want to re-run the sorting experiment tasks,
How can we get "/data/data_sort_8000_{train, val, test}".txt files?
Could you share those files? Or, could you share how you created?

Thanks in advance.

**Comment by pedrohenriqueamartins** [comment]
Hi,

You should run generate_data.py to create the data files, as stated in the README file. 
You might have to change the sequence lenght and the paths on which you want to save the data files. If you wish, you can also change the vocabulary size.

Let me know if you have any doubts.
